before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: addLicense
archives:
  - replacements:
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'SHA256SUMS'
release:
  github:
    owner: hashicorp
    name: addLicense
  header: |
    - Attached to this release are compressed builds of the `addLicense` client
