on: [push, pull_request]
name: linter

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure git for private modules (hashicorp/addLicense)
      run: git config --global url."https://git:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45
